= NetBSD Root on CGD/ZFS
Malte Dehling <mdehling@gmail.com>

This repository currently contains two distinct but related contributions:

1. A patch for the `cgdconfig` command to add ZFS pool verification.
2. The build files for a ramdisk with everything necessary to boot into a
NetBSD system on a ZFS root pool inside a CGD encrypted partition.

Patching the CGD Configuration Utility
--------------------------------------
With this patch, `cgdconfig` can unlock a CGD partition containing a ZFS pool
without the need to add a GPT label in between.  The method used to verify the
ZFS pool is the same as implemented in `usr.sbin/fstyp`.  To apply the patch,
simply run `patch < /path/to/cgdconfig.diff` in your system source directory.

NOTE: The patch is not required to use the ramdisk if you plan on placing a
GPT label inside your CGD partition or use some other means of verification.

Building the Ramdisk
--------------------
The `cgdzfsroot` ramdisk is a straightforward combination of NetBSD's
`cgdroot` and `zfsroot` ramdisks.  Run `patch < /path/to/cgdzfsroot.diff` in
your system source directory to create the necessary files and update your
system.

[source,shell-session]
----
# cd /usr/src
# ./build.sh -u -O /usr/obj -j4 distribution
----

This should produce a kernel module `cgdzfsroot.kmod` containing the ramdisk
in `/usr/obj/distrib/amd64/kmod-cgdzfsroot`.  This will need to go in your
EFI/boot partition.
