= NetBSD Root on CGD/ZFS
Malte Dehling <mdehling@gmail.com>

This repository currently contains two distinct but related contributions:

1. A patch for the `cgdconfig` command to add ZFS pool verification.
2. The build files for a ramdisk with everything necessary to boot into a
NetBSD system on a ZFS root pool inside a CGD encrypted partition.

Patching the CGD Configuration Utility
--------------------------------------
With this patch, `cgdconfig` can unlock a CGD partition containing a ZFS pool
without the need to add a GPT label in between.  The method used to verify the
ZFS pool is the same as implemented in `usr.sbin/fstyp`.  To apply the patch,
simply run `patch < /path/to/sbin_cgdconfig.diff` in your system source
directory.

NOTE: The patch is not required to use the ramdisk if you plan on placing a
GPT label inside your CGD partition or use some other means of verification.

Building the Ramdisk
--------------------
The `cgdzfsroot` ramdisk is a straightforward combination of NetBSD's
`cgdroot` and `zfsroot` ramdisks.  To build it, copy the contents of the `src`
directory to your NetBSD source tree and run the following commands:

[source,shell-session]
----
# cd src/distrib/amd64/ramdisks/ramdisk-cgdzfsroot
# /path/to/tooldir/bin/nbmake-amd64
[...]
# cd src/distrib/amd64/kmod-cgdzfsroot
# /path/to/tooldir/bin/nbmake-amd64
----

This should produce a kernel module `cgdzfsroot.kmod` containing the ramdisk
in `/path/to/objdir/distrib/amd64/kmod-cgdzfsroot`.  This will need to go in
your EFI/boot partition.
